export default {
  ADD_TODO_ITEM: 'ADD_TODO_ITEM',
  EDIT_TODO_ITEM: 'EDIT_TODO_ITEM',
  SET_CURRENT_ITEM: 'SET_CURRENT_ITEM',
  SET_CURRENT_INDEX: 'SET_CURRENT_INDEX',
  DEL_TODO_ITEM: 'DEL_TODO_ITEM'
}
